[project]
name = "python-package"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
  {name = "Wisaroot Lertthaweedech", email = "l.wisaroot@gmail.com"}
]
requires-python = ">=3.10"
dependencies = [
  "bakefile[lib]"
]

[project.scripts]
python-package = "python_package:main"

[dependency-groups]
dev = [
  "deptry>=0.24.0",
  "pre-commit>=4.5.1",
  "pytest-cov>=7.0.0",
  "pytest>=9.0.2",
  "toml-sort>=0.24.3"
]

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[tool.deptry.package_module_name_map]
bakefile = ["bake", "bakelib"]

[tool.uv.sources]
bakefile = {path = "../../", editable = true}
