name: ci

on:
    # Rulesets for main branch
    # - Require status checks to pass -> Require branches to be up to date before merging
    pull_request:
        types: [labeled, unlabeled, opened, synchronize, reopened]

permissions:
    contents: write
    id-token: write

jobs:
    # ====================================================
    # Versioning and Release
    # ====================================================
    check-pre-release:
        name: check-pre-release
        uses: wislertt/zerv/.github/workflows/shared-check-pr-label-and-branch.yml@v0
        with:
            target_label: "pre-release"
            branch_prefix: "release/"

    zerv-versioning:
        name: zerv-versioning
        needs: check-pre-release
        uses: wislertt/zerv/.github/workflows/shared-zerv-versioning.yml@v0
        with:
            schema: ${{ (needs.check-pre-release.outputs.is_valid == 'true' && 'standard-base-prerelease-post') || '' }}

    tag-pre-release:
        name: tag-pre-release
        needs: [zerv-versioning, check-pre-release]
        if: needs.check-pre-release.outputs.is_valid == 'true'
        uses: wislertt/zerv/.github/workflows/shared-create-tags.yml@v0
        with:
            tags: '["${{ fromJson(needs.zerv-versioning.outputs.versions).v_semver }}"]'

    # ====================================================
    # Test and Lint
    # ====================================================
    test:
        uses: ./.github/workflows/test.yml
        secrets:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    pre-commit:
        uses: ./.github/workflows/pre-commit.yml

    # ====================================================
    # Deployment without environment
    # ====================================================
    publish-test-pypi:
        name: publish-to-test-pypi
        if: needs.check-pre-release.outputs.is_valid == 'true'
        needs: [zerv-versioning, check-pre-release, test]
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

            - name: Update version in pyproject.toml
              run: |
                  sed -i.bak 's/^version = .*/version = "${{ fromJson(needs.zerv-versioning.outputs.versions).pep440 }}"/' pyproject.toml
                  grep '^version' pyproject.toml

            - name: Set up Python
              uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
              with:
                  python-version: "3.14"

            - name: Install uv
              uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
              with:
                  version: "latest"

            - name: Build package
              run: uv build

            - name: Publish to Test PyPI
              uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
              with:
                  repository-url: https://test.pypi.org/legacy/
                  verbose: true
