name: publish-python-package

on:
    workflow_call:
        inputs:
            version:
                required: true
                type: string
                description: "PEP440 version string"
            index:
                required: false
                type: string
                description: "Publish index (pypi or testpypi)"
                default: "testpypi"
            python_version:
                required: false
                type: string
                description: "Python version"
        secrets:
            PYPI_API_TOKEN:
                required: true

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: setup-python
              uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
              with:
                  python-version: ${{ inputs.python_version }}

            - name: setup-uv
              uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41 # v7.2.1

            - name: publish
              run: |
                  BAKE_PUBLISH_TOKEN=${{ secrets.PYPI_API_TOKEN }} \
                  bake publish \
                      --index "${{ inputs.index }}" \
                      --version "${{ inputs.version }}"
